# Generated by Django 3.1.6 on 2021-02-19 14:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charities',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجمعية')),
                ('region', models.CharField(max_length=30, verbose_name='المنطقة')),
                ('age', models.IntegerField(choices=[(1, 'أقل من 7 سنوات'), (4, 'من 7 - 18 سنة'), (3, 'من 19 - 35 سنة'), (2, 'أكثر من 60 سنة')], default=1, verbose_name='الفئة العمرية')),
                ('gender', models.IntegerField(choices=[(1, 'ذكور'), (2, 'إناث'), (3, 'ذكور وإناث')], default=1, verbose_name='الفئة النوعية')),
                ('employee_no', models.IntegerField(verbose_name='عدد الموظفين')),
                ('volunteers_no', models.IntegerField(verbose_name='عدد المتطوعين')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'verbose_name_plural': 'الجمعيات الخيرية',
                'ordering': ['-date_created'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='نوع الإعانة')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'verbose_name_plural': 'نوع الإعانات',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='نوع فئة الإعانة')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'verbose_name_plural': 'نوع فئة الإعانات',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=10, verbose_name='رقم الهوية/الإقامة')),
                ('phone_no', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('region', models.CharField(max_length=30, verbose_name='المنطقة')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('gender', models.IntegerField(choices=[(1, 'ذكر'), (2, 'أنثى')], default=1, verbose_name='الجنس')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
            ],
            options={
                'verbose_name_plural': 'المحتاجين',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SegmentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charities', verbose_name='الجمعية')),
                ('segment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.segment', verbose_name='نوع فئة الإعانة')),
            ],
            options={
                'verbose_name_plural': 'فئة انشطة الجميعات',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donations', models.IntegerField(verbose_name='التبرعات والهبات والإشتراكات')),
                ('service_fees', models.IntegerField(verbose_name='رسوم الخدمات')),
                ('zakat', models.IntegerField(verbose_name='الزكاة')),
                ('investments', models.IntegerField(verbose_name='الإستثمارات والأوقاف')),
                ('others', models.IntegerField(verbose_name='أخرى')),
                ('year', models.DateTimeField(verbose_name='السنة')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charities', verbose_name='الجمعية')),
            ],
            options={
                'verbose_name_plural': 'الإيرادات',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='التقييم')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charities', verbose_name='الجمعية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='المحتاج')),
            ],
            options={
                'verbose_name_plural': 'تقييم الجميعات',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.IntegerField(verbose_name='مصاريف تنفيذ الخدمات')),
                ('donations', models.IntegerField(verbose_name='المساعدات والتبرعات')),
                ('admin_expenses', models.IntegerField(verbose_name='مصاريف عمومية وإدارية')),
                ('invest_losses', models.IntegerField(verbose_name='خسائر استثمارات')),
                ('others', models.IntegerField(verbose_name='أخرى')),
                ('year', models.DateTimeField(verbose_name='السنة')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charities', verbose_name='الجمعية')),
            ],
            options={
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'تمت التقديم'), (2, 'جاري المراجعة'), (3, 'جاري الإعانة'), (4, 'تمت الإعانة'), (5, 'مرفوض')], default=1, verbose_name='حالة الإعانة')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charities', verbose_name='الجمعية')),
                ('donated_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donationtype', verbose_name='نوع الإعانة')),
                ('segment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.segment', verbose_name='نوع فئة الإعانة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users', verbose_name='المحتاج')),
            ],
            options={
                'verbose_name_plural': 'طلبات الإعانات',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DoinationActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charities', verbose_name='الجمعية')),
                ('donated_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.segment', verbose_name='نوع الإعانة')),
            ],
            options={
                'verbose_name_plural': 'نوع انشطة الجميعات',
                'ordering': ['-date_created'],
            },
        ),
    ]
