# Generated by Django 3.1.6 on 2021-02-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال'),
        ),
    ]
