# Generated by Django 3.1.6 on 2021-02-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210219_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['-date_created'], 'verbose_name_plural': ' فئة المحتاجين'},
        ),
        migrations.AlterModelOptions(
            name='segmentactivity',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'الفئة المستهدفة للجمعية'},
        ),
    ]
