# Generated by Django 3.1.6 on 2021-02-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210219_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='status',
            field=models.IntegerField(choices=[(1, 'تم التقديم'), (2, 'جاري المراجعة'), (3, 'جاري الإعانة'), (4, 'تمت الإعانة'), (5, 'مرفوض')], default=1, verbose_name='حالة الإعانة'),
        ),
    ]
